//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assortie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adherent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adherent()
        {
            this.HistoriquePaiements = new HashSet<HistoriquePaiement>();
            this.SortieAdherents = new HashSet<SortieAdherent>();
        }
    
        public int IdAdherent { get; set; }
        public int IdAssociation { get; set; }
        public string Matricule { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public bool Cotisation { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool Responsable { get; set; }
        public decimal Solde { get; set; }
    
        public virtual Association Association { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriquePaiement> HistoriquePaiements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SortieAdherent> SortieAdherents { get; set; }
    }
}
