//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assortie.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssortieEntities : DbContext
    {
        public AssortieEntities()
            : base("name=AssortieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adherent> Adherents { get; set; }
        public virtual DbSet<Association> Associations { get; set; }
        public virtual DbSet<HistoriquePaiement> HistoriquePaiements { get; set; }
        public virtual DbSet<Sortie> Sorties { get; set; }
        public virtual DbSet<SortieAdherent> SortieAdherents { get; set; }
    }
}
