//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assortie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortieAdherent
    {
        public int IdSortie { get; set; }
        public int IdAdherent { get; set; }
        public int IdAssociation { get; set; }
    
        public virtual Adherent Adherent { get; set; }
        public virtual Association Association { get; set; }
        public virtual Sortie Sortie { get; set; }
    }
}
